/*
 * audio_songs_generated.h - Auto-generated song definitions
 * Generated by scripts/generate_audio_code.py
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Modify config.yaml and MusicXML files in songs/ folder instead.
 *
 * Copyright (c) 2025 monkeyToneCircuits
 * Licensed under CC-BY-NC 4.0
 */

#ifndef AUDIO_SONGS_GENERATED_H_
#define AUDIO_SONGS_GENERATED_H_

#include <stdint.h>

// Note: This file is included from audio.h AFTER audio_note_t and song_config_t are defined
// Do not include audio.h here to avoid circular dependency

// ============================================================================
// MELODY ENUMERATION
// ============================================================================

typedef enum
{
    MELODY_NONE = 0,
    MELODY_JINGLE_BELLS,
    MELODY_OH_TANNENBAUM,
    MELODY_OH_DU_FROHLICHE,
    MELODY_SCHNEEFLOCKCHEN_WEISSROCKCHEN,
    MELODY_STILLE_NACHT_CHIPVERSION,
    MELODY_THE_FIRST_NOEL_TRUMPET_ONLY,
    MELODY_KOMMET_IHR_HIRTEN,
    MELODY_TRADITIONAL_MUSIC_I_SAW_THREE_SHIPS_COME_SAILING_IN,
    MELODY_TEST_TONE,
    MELODY_COUNT
} melody_id_t;

// ============================================================================
// FUNCTION DECLARATIONS
// ============================================================================

const audio_note_t *get_melody_data(melody_id_t melody_id, uint8_t *note_count);
const song_config_t *get_song_config(melody_id_t melody_id);

// ============================================================================
// ENABLED SONGS DECLARATIONS
// ============================================================================

#if ENABLE_SONG_ROTATION
extern const melody_id_t enabled_songs[];
extern const uint8_t ENABLED_SONG_COUNT;
#endif

#endif // AUDIO_SONGS_GENERATED_H_
