#ifndef HARDWARE_CONFIG_GENERATED_H_
#define HARDWARE_CONFIG_GENERATED_H_

/*
 * hardware_config_generated.h - Auto-generated hardware configuration
 * Generated by scripts/generate_audio_code.py from config.yaml
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Modify config.yaml hardware section instead.
 *
 * Copyright (c) 2025 monkeyToneCircuits
 * Licensed under CC-BY-NC 4.0
 */

// ============================================================================
// HARDWARE CONFIGURATION - From config.yaml
// ============================================================================

// Sensor Configuration
#define BREATH_SENSITIVITY 1
#define SENSOR_UPDATE_RATE_MS 5

// LED Configuration
#define LED_BRIGHTNESS_DEFAULT 30
#define CANDLE_FLICKER_SPEED 150
#define CANDLE_FLICKER_INTENSITY 70

// Audio Configuration
#define AUDIO_MAX_FREQUENCY 4000
#define AUDIO_MIN_FREQUENCY 100
#define AUDIO_DEFAULT_VOLUME 128
#define SONG_COOLDOWN_MS 3000
#define AUDIO_NOTE_GAP_MS 50
#define STARTUP_MELODY_ENABLED false

#endif // HARDWARE_CONFIG_GENERATED_H_
